### PR TITLE
🐛 Fix compiler error (#100)

### LINKED ISSUE #100: 🐞 Compiler Error in admin-app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you `make start` you get:

```
TypeScript error in C:/dev/ElectionGuard/electionguard-ui/packages/admin-app/src/components/ElectionSetupWizard/ElectionSetupWizard.tsx(1,33):
Module '"@electionguard/api-client"' has no exported member 'getGuardianApiClient'.  TS2305

  > 1 | import { AsyncResult, JointKey, getGuardianApiClient } from '@electionguard/api-client';
      |                                 ^
    2 | import { Box } from '@material-ui/core';
    3 | import React, { useState } from 'react'
```

### Expected Behavior

It should compile and run

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Windows, but probably Ubuntu too
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lprichar**
### Issue

Fixes #100 

### Description

When running the api-client you used to get an error: `Module '"@electionguard/api-client"' has no exported member 'getGuardianApiClient`.  This fixes it.

### Testing

Run `make start`, it should run without errors and the admin-app should show up.

### CODE REVIEW

File: packages/api-client/src/index.ts [hunk 1]
```diff
@@ -1,3 +1,5 @@
 export * from './api';
 export * from './data';
 export * from './models';
+
+export { default as ApiClientFactory } from './api/ApiClientFactory';
```
Comment (lprichar) [inline packages/api-client/src/index.ts:5]: ^ this is wrong.  It works, but typically the new class would be imported and reexported in `/src/api/index.ts`, and this file would be untouched.  I just couldn't get it to work the way I have on other projects and I was wasting a lot of time on it.  If this is good enough, that's fine, it works, else I would greatly appreciate advice on what I'm doing wrong.

Comment (lprichar) [reply packages/api-client/src/index.ts]: fixed

File: packages/api-client/.eslintrc.json [hunk 2]
```diff
@@ -4,6 +4,7 @@
         "@typescript-eslint/no-explicit-any": "off",
         "@typescript-eslint/no-unused-vars": "off",
         "@typescript-eslint/explicit-module-boundary-types": "off",
-        "import/extensions": "off"
+        "import/extensions": "off",
+        "import/prefer-default-export": "off"
```
Comment (lprichar) [inline packages/api-client/.eslintrc.json:8]: Else I get the linting error: `Prefer default export  import/prefer-default-export` in the `ApiClientFactory.ts` file

File: packages/api-client/src/index.ts [hunk 3]
```diff
@@ -1,3 +1,3 @@
-export * from './api';
+export * from './api/index';
```
Comment (lprichar) [inline packages/api-client/src/index.ts:1]: This reexport from the index submodule has to be here to get the ApiClientFactory since exporting from ./api doesn't expose it

File: packages/api-client/src/api/index.ts [hunk 4]
```diff
@@ -1,2 +1,4 @@
 export * from './Api';
 export * from './functions';
+
+export { ApiClientFactory } from './ApiClientFactory';
```
Comment (lprichar) [inline packages/api-client/src/api/index.ts:4]: I couldn't get `export *` in this nested submodule to expose ApiClientFactory, even when it's not default.  I'd welcome changes, but I'm happy with this approach

**Review by SteveMaier-IRT — APPROVED** [review]
